### ISSUE TITLE
[bug]: greylist also applies on authenticated sender

### ISSUE THREAD

**Issue by johansmitsnl** [stalwartlabs/smtp-server#27]
### What happened?

When I try to send a email to the user I get a greylist message. But greylist should only apply on incomming e-mail from external servers.

### How can we reproduce the problem?

I used the example from: https://stalw.art/docs/smtp/filter/sieve#greylisting

### Version

v0.3.1

### Which directory type are you using for local address resolution?

LDAP

### What operating system are you using?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdecimus** [comment]
There are two ways to avoid this:

- Use a rule to call the greylist sieve script only for unuthenticated users.
- From within your sieve script add an 'if' using the authenticated-as environment variable to only greylist unauthenticated sessions.
