### ISSUE TITLE
Only the first TLS certificate is used rather than the full chain

### ISSUE THREAD

**Issue by ngocnha** [stalwartlabs/smtp-server#3]
Failed to send GET request: error sending request for url (https://mail.my-server.com:8686/report/list?): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

I am using the same certificate obtained from Let's Encrypt and the same domain for both the JMAP server and SMTP, but while JMAP works perfectly, SMTP fails.

**Comment by mdecimus** [comment]
There are two things you can check:

1. Compare the certificates returned by both servers using `openssl`:

```
openssl s_client -showcerts -connect mail.my-server.com:8686 </dev/null  # Replace with the SMTP URL
openssl s_client -showcerts -connect jmap.my-server.com:443 </dev/null   # Replace with the JMAP URL
```

2. Make sure that Stalwart SMTP is using the Let's Encrypt certificate. Open `/usr/local/stalwart-smtp/etc/config.toml` and look for the `[certificate]` section, it should look something like this:

```
[certificate."default"]
cert = "file:///usr/local/stalwart-smtp/etc/certs/tls.crt"
private-key = "file:///usr/local/stalwart-smtp/etc/private/tls.key"
```

Then verify that `cert` and `private-key` are actually pointing to the Let's Encrypt certificate.

**Comment by ngocnha** [comment]
After following your suggestions, I realized that the certificate and path were correct. However, the certificate I am using is a certificate chain that contains multiple certificates, including my certificate and the issuer certificates. JMAP was able to read and work with the entire chain, but SMTP only read the first certificate and failed.

**Comment by ngocnha** [comment]
I manually trusted the Let's Encrypt issuer certificate on my system, but the result did not change.

https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html

**Comment by ngocnha** [comment]
Fixed, this is latest result:

openssl s_client -showcerts -connect mail.my-server.com:8686 </dev/null
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = mail.my-server.com
verify return:1
---
Certificate chain
 0 s:CN = mail.my-server.com
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 16 16:50:26 2023 GMT; NotAfter: Apr 16 16:50:25 2023 GMT
-----BEGIN CERTIFICATE-----
MIIFJzCCBA+gAwIBAgISA12Hr5Z028LYQDjgH1Ja090BMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzAxMTYxNjUwMjZaFw0yMzA0MTYxNjUwMjVaMBwxGjAYBgNVBAMT
