### ISSUE TITLE
[bug]: "Undefined certificate id for listener ..."

### ISSUE THREAD

**Issue by jdrouet** [stalwartlabs/smtp-server#41]
### What happened?

I installed `stalwart-smtp` using everything in local with `sqlite` and now the server is not starting.

When I run `/opt/stalwart-smtp/bin/stalwart-smtp --config /opt/stalwart-smtp/etc/config.toml` I get the following error: `Invalid configuration: Undefined certificate id for listener "imap".`.
I tried to comment some included files in `/opt/stalwart-smtp/etc/config.toml` but I keep getting similar errors.

### How can we reproduce the problem?

Install `stalwart-smtp` (only) with the script on a debian machine.

### Version

v0.5.x

### Which directory type are you using for local address resolution?

SQLite

### What operating system are you using?

Linux

### Relevant log output

```shell
Invalid configuration: Undefined certificate id for listener "imap".
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdecimus** [comment]
Do you have a valid certificate defined in `server.tls.certificate` or `server.imap.tls.certificate`?

**Comment by jdrouet** [comment]
I used the script to install the smtp server, it should have started one, right?

**Comment by mdecimus** [comment]
The install script generates a self-signed certificate. Since you are using the SMTP only package, try commenting out the server.imap section of the config file.
