### ISSUE TITLE
ehlo fqdn default config error

### ISSUE THREAD

**Issue by TuxCoder** [stalwartlabs/smtp-server#6]
There is a difference between the example config and the parsed config.

in the example the here: https://github.com/stalwartlabs/smtp-server/blob/415f98af15c9bc98c0ced5e2cad08e2de6569bc7/resources/config/config.toml#L77

the paramter `reject-non-fqdn` is used.

but in the code here: https://github.com/stalwartlabs/smtp-server/blob/415f98af15c9bc98c0ced5e2cad08e2de6569bc7/src/config/session.rs#L205

the paramter `session.ehlo.reject-invalid` is used.

I think the code is the type as the other varibles are also more like `reject_non_fqdn`.

**Comment by mdecimus** [comment]
Thanks for reporting this. It was fixed.
